apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-worker
  labels:
    app.kubernetes.io/name: reservation-worker
spec:
  # 예약 Worker는 아직 기능 구현 전이면 0으로 유지해도 됩니다.
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: reservation-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reservation-worker
        app.kubernetes.io/part-of: nowait
    spec:
      serviceAccountName: nowait-worker
      containers:
        - name: reservation-worker
          image: nowait-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ROLE
              value: "reservation-worker"
          envFrom:
            - configMapRef:
                name: nowait-app-config
            - secretRef:
                name: nowait-app-secret
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
