apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nowait-api
  labels:
    app.kubernetes.io/name: nowait-api
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nowait-api
                port:
                  number: 80
