apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - deployment-api.yaml
  - deployment-waiting-worker.yaml
  - deployment-reservation-worker.yaml
  - service-api.yaml
  - ingress.yaml
  - hpa-api.yaml

commonLabels:
  app.kubernetes.io/part-of: nowait
