apiVersion: v1
kind: ServiceAccount
metadata:
  name: nowait-api
  labels:
    app.kubernetes.io/name: nowait-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nowait-worker
  labels:
    app.kubernetes.io/name: nowait-worker
