apiVersion: apps/v1
kind: Deployment
metadata:
  name: nowait-api
  namespace: {{ .Values.namespace }}
  labels:
    app: nowait-api
    team: team6
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nowait-api
  template:
    metadata:
      labels:
        app: nowait-api
        team: team6
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: nowait-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: nowait-api-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
