{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nowait-api
  namespace: {{ .Values.namespace }}
  labels:
    app: nowait-api
    team: team6
spec:
  scaleTargetRef:
    name: nowait-api
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "{{ .Values.keda.targetCPUUtilizationPercentage }}"
    - type: memory
      metricType: Utilization
      metadata:
        value: "{{ .Values.keda.targetMemoryUtilizationPercentage }}"
{{- end }}
