apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nowait-app-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: nowait-app-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /team6/nowait/dev/rds/host

    - secretKey: DB_PORT
      remoteRef:
        key: /team6/nowait/dev/rds/port

    - secretKey: DB_NAME
      remoteRef:
        key: /team6/nowait/dev/rds/database

    - secretKey: DB_USERNAME
      remoteRef:
        key: /team6/nowait/dev/rds/username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: /team6/nowait/dev/rds/password

    - secretKey: REDIS_HOST
      remoteRef:
        key: /team6/nowait/dev/redis/host

    - secretKey: REDIS_PORT
      remoteRef:
        key: /team6/nowait/dev/redis/port

    - secretKey: JWT_SECRET
      remoteRef:
        key: /team6/nowait/dev/jwt/secret

    - secretKey: AWS_REGION
      remoteRef:
        key: /team6/nowait/dev/aws/region

    - secretKey: S3_IMAGE_BUCKET
      remoteRef:
        key: /team6/nowait/dev/s3/image-bucket

    - secretKey: S3_IMAGE_PREFIX
      remoteRef:
        key: /team6/nowait/dev/s3/image-prefix

    - secretKey: APP_ALLOWED_ORIGINS
      remoteRef:
        key: /team6/nowait/dev/app/allowed-origins
