apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nowait-api-dev
  namespace: argocd
  labels:
    team: team6
    env: dev
    app: nowait-api
spec:
  project: nowait
  source:
    repoURL: https://github.com/CLD-05/team6-nowait-config.git
    targetRevision: main
    path: charts/nowait-api
    helm:
      valueFiles:
        - ../../envs/dev/api-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nowait
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
