# dev 환경 api 오버라이드 값

replicaCount: 1

image:
  tag: "dev-6e51623"  # cicd.yml에서 이미지 태그 자동 갱신

ingress:
  host: dev-api.nowait.internal  # 실제 도메인으로 교체 필요

hpa:
  minReplicas: 1
  maxReplicas: 3

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  SPRING_PROFILES_ACTIVE: "dev"

externalSecret:
  secrets:
    - secretKey: api
      remoteKey: team6-nowait/dev/api
    - secretKey: redis
      remoteKey: team6-nowait/dev/redis

namespace: nowait-dev
