apiVersion: apps/v1
kind: Deployment
metadata:
  name: nowait-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: nowait-worker
    team: team6
spec:
  {{- if not (or .Values.hpa.enabled (and .Values.keda .Values.keda.enabled)) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: nowait-worker
  template:
    metadata:
      labels:
        app: nowait-worker
        team: team6
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: nowait-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: nowait-worker-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
            - name: REDIS_SSL_ENABLED
              value: {{ .Values.env.REDIS_SSL_ENABLED | quote }}
            {{- if .Values.env.DB_URL }}
            - name: DB_URL
              value: {{ .Values.env.DB_URL | quote }}
            {{- end }}
            {{- if .Values.env.WAITING_WORKER_BATCH_SIZE }}
            - name: WAITING_WORKER_BATCH_SIZE
              value: {{ .Values.env.WAITING_WORKER_BATCH_SIZE | quote }}
            {{- end }}
            {{- if .Values.env.WAITING_WORKER_CHUNK_SIZE }}
            - name: WAITING_WORKER_CHUNK_SIZE
              value: {{ .Values.env.WAITING_WORKER_CHUNK_SIZE | quote }}
            {{- end }}
            {{- if .Values.env.RESERVATION_WORKER_BATCH_SIZE }}
            - name: RESERVATION_WORKER_BATCH_SIZE
              value: {{ .Values.env.RESERVATION_WORKER_BATCH_SIZE | quote }}
            {{- end }}
            {{- if .Values.env.RESERVATION_WORKER_CHUNK_SIZE }}
            - name: RESERVATION_WORKER_CHUNK_SIZE
              value: {{ .Values.env.RESERVATION_WORKER_CHUNK_SIZE | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 18

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            failureThreshold: 6