{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nowait-worker-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: nowait-worker
    team: team6
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: nowait-worker-secret
    creationPolicy: Owner

  {{- if .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- range .Values.externalSecret.dataFrom }}
    - extract:
        key: {{ .key | quote }}
    {{- end }}
  {{- end }}

  {{- if .Values.externalSecret.data }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
        property: {{ .remoteRef.property | quote }}
    {{- end }}
  {{- end }}
{{- end }}